# Generated by Django 4.2.7 on 2023-11-28 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TblCidade",
            fields=[
                ("cdd_id", models.AutoField(primary_key=True, serialize=False)),
                ("cdd_nome", models.CharField(max_length=100)),
                ("cdd_uf", models.CharField(max_length=45)),
                ("cdd_ativo", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="TblFidelidade",
            fields=[
                ("fid_id", models.AutoField(primary_key=True, serialize=False)),
                ("fid_qtdemeses", models.IntegerField(unique=True)),
                ("fid_ativo", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="TblItens",
            fields=[
                ("item_id", models.AutoField(primary_key=True, serialize=False)),
                ("item_nome", models.CharField(max_length=25)),
                (
                    "item_ordem",
                    models.IntegerField(
                        blank=True,
                        db_comment="Cadastre os itens que agregam maior valor no topo da lista",
                        null=True,
                        unique=True,
                    ),
                ),
                ("item_icone", models.CharField(blank=True, max_length=45, null=True)),
                ("item_detalhe", models.TextField(blank=True, null=True)),
                (
                    "item_linkexterno",
                    models.CharField(blank=True, max_length=45, null=True),
                ),
                ("item_ativo", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="TblPlano",
            fields=[
                ("plan_id", models.AutoField(primary_key=True, serialize=False)),
                ("plan_nome", models.CharField(blank=True, max_length=100, null=True)),
                ("plan_valor", models.FloatField(blank=True, null=True)),
                ("plan_ordem", models.IntegerField(blank=True, null=True, unique=True)),
                ("plan_taxaup", models.FloatField(blank=True, null=True)),
                ("plan_taxadown", models.FloatField(blank=True, null=True)),
                ("plan_destacarplano", models.IntegerField()),
                (
                    "plan_textdestaque",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("plan_tipocliente", models.CharField(max_length=20)),
                ("plan_tipolink", models.CharField(max_length=13)),
                ("plan_combo", models.IntegerField()),
                ("plan_icon", models.CharField(blank=True, max_length=255, null=True)),
                ("plan_ativo", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="TblPlaniten",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        default="1",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="planos.tblitens",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        default="1",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="planos.tblplano",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TblCiddplan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cdd",
                    models.ForeignKey(
                        default="1",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="planos.tblcidade",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        default="1",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="planos.tblplano",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TblAcordos",
            fields=[
                ("acor_id", models.AutoField(primary_key=True, serialize=False)),
                ("acor_valor", models.FloatField()),
                ("acor_sla", models.CharField(blank=True, max_length=30, null=True)),
                ("acor_padrao", models.IntegerField()),
                ("acor_ativo", models.IntegerField()),
                (
                    "acor_fid",
                    models.ForeignKey(
                        default="1",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="planos.tblfidelidade",
                    ),
                ),
                (
                    "acor_plan",
                    models.ForeignKey(
                        default="1",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="planos.tblplano",
                    ),
                ),
            ],
        ),
    ]
