# Generated by Django 4.2.7 on 2023-12-01 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TblCidade",
            fields=[
                ("cdd_id", models.AutoField(primary_key=True, serialize=False)),
                ("cdd_nome", models.CharField(max_length=100)),
                ("cdd_uf", models.CharField(max_length=2)),
                ("cdd_ativo", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="TblFidelidade",
            fields=[
                ("fid_id", models.AutoField(primary_key=True, serialize=False)),
                ("fid_qtdemeses", models.IntegerField()),
                ("fid_tipocliente", models.CharField(max_length=11)),
                ("fid_ativo", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="TblItens",
            fields=[
                ("item_id", models.AutoField(primary_key=True, serialize=False)),
                ("item_nome", models.CharField(max_length=25)),
                ("item_scm", models.IntegerField(blank=True, null=True)),
                ("item_ordem", models.IntegerField(blank=True, null=True, unique=True)),
                ("item_icone", models.CharField(blank=True, max_length=255, null=True)),
                ("item_detalhe", models.TextField(blank=True, null=True)),
                (
                    "item_linkexterno",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("item_ativo", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="TblPlano",
            fields=[
                ("plan_id", models.AutoField(primary_key=True, serialize=False)),
                ("plan_nome", models.CharField(blank=True, max_length=100, null=True)),
                ("plan_valor", models.FloatField(blank=True, null=True)),
                ("plan_ordem", models.IntegerField(blank=True, null=True, unique=True)),
                ("plan_taxaup", models.FloatField()),
                ("plan_taxadown", models.FloatField()),
                ("plan_destacarplano", models.IntegerField()),
                (
                    "plan_textdestaque",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("plan_tipocliente", models.CharField(max_length=11)),
                ("plan_tipolink", models.CharField(max_length=13)),
                ("plan_combo", models.IntegerField()),
                ("plan_icon", models.CharField(blank=True, max_length=255, null=True)),
                ("plan_ativo", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="TblItensCombo",
            fields=[
                ("icomb_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "icomb_item",
                    models.ForeignKey(
                        db_column="icomb_item_ID",
                        default=1,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="planos.tblitens",
                    ),
                ),
                (
                    "icomb_plan",
                    models.ForeignKey(
                        db_column="icomb_plan_ID",
                        default=1,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="planos.tblplano",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TblAcordos",
            fields=[
                ("acor_id", models.AutoField(primary_key=True, serialize=False)),
                ("acor_valor", models.FloatField(db_column="acor_Valor")),
                ("acor_sla", models.CharField(blank=True, max_length=30, null=True)),
                ("acor_padrao", models.IntegerField()),
                ("acor_ativo", models.IntegerField()),
                (
                    "acor_fid",
                    models.ForeignKey(
                        db_column="acor_fid_ID",
                        default=1,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="planos.tblfidelidade",
                    ),
                ),
                (
                    "acor_plan",
                    models.ForeignKey(
                        db_column="acor_plan_ID",
                        default=1,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="planos.tblplano",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TblAbrangenciaPlano",
            fields=[
                ("abrang_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "abrang_cdd",
                    models.ForeignKey(
                        db_column="abrang_cdd_ID",
                        default=1,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="planos.tblcidade",
                    ),
                ),
                (
                    "abrang_plan",
                    models.ForeignKey(
                        db_column="abrang_plan_ID",
                        default=1,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="planos.tblplano",
                    ),
                ),
            ],
        ),
    ]
